additionalScrapeConfigs:
  - job_name: 'aiops-quality'
    honor_labels: true
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: "true"
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __meta_kubernetes_pod_port_name
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
