apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: infra-tools
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        mode: standalone
        replicas: 1
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        rootUser: minio
        rootPassword: minio123
        buckets:
          - name: mlflow-artifacts
            policy: none
            purge: false
            versioning: false
        service:
          type: ClusterIP
        persistence:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true   # <-- namespace is created automatically
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
