apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: bitnami-oci
    targetRevision: 16.7.27
    chart: postgresql
    helm:
      values: |
        auth:
          username: mlflow
          password: mlflow123
          database: mlflow
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true   # <-- namespace is created automatically
