apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.7.1
    helm:
      values: |
        service:
          type: ClusterIP
          port: 5000
        backendStore:
          postgres:
            enabled: true
            host: postgres-postgresql.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow123
            driver: psycopg2
        # Mlflow blob storage settings
        artifactRoot:
          # -- Specifies the default artifact root.
          defaultArtifactRoot: "s3://mlflow-artifacts"
        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: "http://minio.mlflow.svc.cluster.local:9000"
          AWS_ACCESS_KEY_ID: "minio"
          AWS_SECRET_ACCESS_KEY: "minio123"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true   # <-- namespace is created automatically
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
